PartyInvites/PartyInvites/Components/CounterViewComponent.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using PartyInvites.Abstract;
using PartyInvites.Models.ViewModels;

namespace PartyInvites.Components
{
    public class CounterViewComponent : ViewComponent
    {
	    private readonly IRepository _repository;

	    public CounterViewComponent(IRepository repository)
	    {
		    _repository = repository;
	    }

	    public IViewComponentResult Invoke()
	    {
		    var responses = _repository.GetAllResponses().ToList();
		    return View(new CounterViewModel
		    {
			    ResponseAmount = responses.Count,
				AttendingAmount = responses.Count(r => r.WillAttend == true)
		    });
	    }
    }
}

PartyInvites/PartyInvites/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<title>@ViewData["Title"]</title>
	<link href="https://fonts.googleapis.com/css?family=Roboto:300" rel="stylesheet">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link rel="stylesheet" href="/css/style.css" />
	<script src="~/lib/jquery/dist/jquery.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-backstretch/2.0.4/jquery.backstretch.min.js"></script>
</head>
<body>
	<div class="content-wrapper">
		<div id="navbar">
			<a asp-controller="Home" asp-action="Index"><i class="material-icons glyphicon-home">home</i></a>
			<ul>
				<li><a asp-controller="Home" asp-action="Index">Home</a></li>
				<li><a asp-controller="Home" asp-action="ListResponses">Attendance</a></li>
				@if (User.Identity.IsAuthenticated)
				{
					<li class="logout"><a asp-action="Logout" asp-controller="Account">Log Out</a></li>
				}
				<li class="counter"><a asp-controller="Home" asp-action="ListResponses">@await Component.InvokeAsync("Counter")</a></li>
			</ul>
		</div>

		@RenderBody()

	</div>

	<script> $.backstretch("@Url.Content("~/images/_DSC0212.jpg")"); </script>

</body>
</html>